#! /bin/sh

if qmake-qt4 --version >/dev/null 2>&1
then
    BINQMAKE=qmake-qt4
elif qmake4 --version >/dev/null 2>&1
then
    BINQMAKE=qmake4
elif qmake --version >/dev/null 2>&1
then
    BINQMAKE=qmake
elif $HOME/Qt/5.3/clang_64/bin/qmake --version >/dev/null 2>&1
then
	BINQMAKE=$HOME/Qt/5.3/clang_64/bin/qmake
elif $HOME/Qt/5.4/clang_64/bin/qmake --version >/dev/null 2>&1
then
	BINQMAKE=$HOME/Qt/5.3/clang_64/bin/qmake
else
    echo qmake not found
	exit
fi

if cmake >/dev/null 2>&1
    echo cmake not found
	exit
fi

cd openjpeg
cmake -DBUILD_SHARED_LIBS:BOOL=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=usr .
make
make install
cd ..

cd ffmpeg
chmod u+x configure
chmod u+x version.sh
if yasm --version >/dev/null 2>&1
then
    ./configure --enable-gpl --enable-version3 --disable-shared --enable-static --disable-swscale-alpha --disable-doc --disable-ffplay --disable-ffprobe --disable-ffserver --disable-debug --enable-libopenjpeg --disable-decoder=jpeg2000 --extra-cflags="-I../openjpeg/usr/include" --extra-ldflags="-L../openjpeg/usr/lib"
else
    cd ../yasm/
    ./configure --prefix=`pwd`/usr
    make
    make install

    cd ../ffmpeg
    ./configure --enable-gpl --enable-version3 --disable-shared --enable-static --disable-swscale-alpha --disable-doc --disable-ffplay --disable-ffprobe --disable-ffserver --disable-debug --enable-libopenjpeg --disable-decoder=jpeg2000 --extra-cflags="-I../openjpeg/usr/include" --extra-ldflags="-L../openjpeg/usr/lib" --yasmexe=../yasm/usr/bin/yasm
fi

make
cd ..

cd qwt
$BINQMAKE
make
cd ..

cd qctools/Project/QtCreator
if sw_vers >/dev/null 2>&1
then
	#Qt 5.2 can not well detect the platform version for 10.9 then FFmpeg static link fails
	MAJOR_MAC_VERSION=$(sw_vers -productVersion | awk -F '.' '{print $1 "." $2}')
	$BINQMAKE QMAKE_MAC_SDK=macosx$MAJOR_MAC_VERSION
else
	$BINQMAKE
fi
make
cd ../../..

echo QCTools binary is in qctools/Project/QtCreator
