#! /bin/bash

# if on Ubuntu start with this setup
# sudo apt-get install git qt5-default cmake g++ yasm libbz2-dev

# could be also required (Ubuntu 14.04 LTS): 
# sudo apt-get install zlib1g-dev
# sudo apt-get install libgl1-mesa-dev
# sudo apt-get install pkg-config

if qmake --version >/dev/null 2>&1 ; then
    BINQMAKE=qmake
elif qmake-qt5 --version >/dev/null 2>&1 ; then
    BINQMAKE=qmake-qt5
elif qmake5 --version >/dev/null 2>&1 ; then
    BINQMAKE=qmake5
elif qmake-qt4 --version >/dev/null 2>&1 ; then
    BINQMAKE=qmake-qt4
elif qmake4 --version >/dev/null 2>&1 ; then
    BINQMAKE=qmake4
elif $HOME/Qt/5.3/clang_64/bin/qmake --version >/dev/null 2>&1 ; then
    BINQMAKE=$HOME/Qt/5.3/clang_64/bin/qmake
elif $HOME/Qt/5.4/clang_64/bin/qmake --version >/dev/null 2>&1 ; then
    BINQMAKE=$HOME/Qt/5.3/clang_64/bin/qmake
else
    echo qmake not found
    exit
fi

if [ ! $(which cmake) ] ; then
    echo cmake not found
    exit
fi

SCRIPT_DIR=$(cd $(dirname "$0") && pwd)
echo "SCRIPT_DIR: " + $SCRIPT_DIR

INSTALL_DIR=$(cd $(dirname "$0") && cd ../../.. && pwd)
cd "$INSTALL_DIR"

source $SCRIPT_DIR/init_blackmagic.sh
source $SCRIPT_DIR/init_ffmpeg.sh
source $SCRIPT_DIR/init_qwt.sh
source $SCRIPT_DIR/build_qctools.sh