#!/bin/sh

#if [ $# != 3 ]; then
# echo "usage: mkdmg appname version"
# exit 0
#fi

APPNAME="$1"
VERSION="$2"
FILES="$3"

APPNAME="QCTools"
VERSION="0.7.3"
SIGNATURE="MediaArea.net"

DMG="tmp-${APPNAME}.dmg"
FILES="tmp-${APPNAME}"

# Create the package
rm -f "{FILES}"
mkdir "${FILES}"
mkdir "${FILES}/${APPNAME}.app"
cp -R "../QtCreator/${APPNAME}.app" "${FILES}/"
sed -i '' -e "s/VERSION/${VERSION}/g" "${FILES}/${APPNAME}.app/Contents/Info.plist"
macdeployqt "${FILES}/${APPNAME}.app"

#Temporary, due to Qt 5.3 not copying Info.plist
cp "${HOME}/Qt/5.3/clang_64/lib/QtCore.framework/Contents/Info.plist" "${FILES}/${APPNAME}.app/Contents/Frameworks/QtCore.framework/Resources/"
cp "${HOME}/Qt/5.3/clang_64/lib/QtGui.framework/Contents/Info.plist" "${FILES}/${APPNAME}.app/Contents/Frameworks/QtGui.framework/Resources/"
cp "${HOME}/Qt/5.3/clang_64/lib/QtPrintSupport.framework/Contents/Info.plist" "${FILES}/${APPNAME}.app/Contents/Frameworks/QtPrintSupport.framework/Resources/"
cp "${HOME}/Qt/5.3/clang_64/lib/QtWidgets.framework/Contents/Info.plist" "${FILES}/${APPNAME}.app/Contents/Frameworks/QtWidgets.framework/Resources/"

codesign -f -s "Developer ID Application: ${SIGNATURE}" --verbose "${FILES}/${APPNAME}.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore"
codesign -f -s "Developer ID Application: ${SIGNATURE}" --verbose "${FILES}/${APPNAME}.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui"
codesign -f -s "Developer ID Application: ${SIGNATURE}" --verbose "${FILES}/${APPNAME}.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/QtPrintSupport"
codesign -f -s "Developer ID Application: ${SIGNATURE}" --verbose "${FILES}/${APPNAME}.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets"

codesign -f -s "Developer ID Application: ${SIGNATURE}" --verbose "${FILES}/${APPNAME}.app/Contents/Frameworks/QtCore.framework"
codesign -f -s "Developer ID Application: ${SIGNATURE}" --verbose "${FILES}/${APPNAME}.app/Contents/Frameworks/QtGui.framework"
codesign -f -s "Developer ID Application: ${SIGNATURE}" --verbose "${FILES}/${APPNAME}.app/Contents/Frameworks/QtPrintSupport.framework"
codesign -f -s "Developer ID Application: ${SIGNATURE}" --verbose "${FILES}/${APPNAME}.app/Contents/Frameworks/QtWidgets.framework"

codesign -f -s "Developer ID Application: ${SIGNATURE}" --verbose "${FILES}/${APPNAME}.app/Contents/PlugIns/accessible/libqtaccessiblewidgets.dylib"
codesign -f -s "Developer ID Application: ${SIGNATURE}" --verbose "${FILES}/${APPNAME}.app/Contents/PlugIns/imageformats/libqdds.dylib"
codesign -f -s "Developer ID Application: ${SIGNATURE}" --verbose "${FILES}/${APPNAME}.app/Contents/PlugIns/imageformats/libqgif.dylib"
codesign -f -s "Developer ID Application: ${SIGNATURE}" --verbose "${FILES}/${APPNAME}.app/Contents/PlugIns/imageformats/libqicns.dylib"
codesign -f -s "Developer ID Application: ${SIGNATURE}" --verbose "${FILES}/${APPNAME}.app/Contents/PlugIns/imageformats/libqico.dylib"
codesign -f -s "Developer ID Application: ${SIGNATURE}" --verbose "${FILES}/${APPNAME}.app/Contents/PlugIns/imageformats/libqjp2.dylib"
codesign -f -s "Developer ID Application: ${SIGNATURE}" --verbose "${FILES}/${APPNAME}.app/Contents/PlugIns/imageformats/libqjpeg.dylib"
codesign -f -s "Developer ID Application: ${SIGNATURE}" --verbose "${FILES}/${APPNAME}.app/Contents/PlugIns/imageformats/libqmng.dylib"
codesign -f -s "Developer ID Application: ${SIGNATURE}" --verbose "${FILES}/${APPNAME}.app/Contents/PlugIns/imageformats/libqtga.dylib"
codesign -f -s "Developer ID Application: ${SIGNATURE}" --verbose "${FILES}/${APPNAME}.app/Contents/PlugIns/imageformats/libqtiff.dylib"
codesign -f -s "Developer ID Application: ${SIGNATURE}" --verbose "${FILES}/${APPNAME}.app/Contents/PlugIns/imageformats/libqwbmp.dylib"
codesign -f -s "Developer ID Application: ${SIGNATURE}" --verbose "${FILES}/${APPNAME}.app/Contents/PlugIns/imageformats/libqwebp.dylib"
codesign -f -s "Developer ID Application: ${SIGNATURE}" --verbose "${FILES}/${APPNAME}.app/Contents/PlugIns/platforms/libqcocoa.dylib"
codesign -f -s "Developer ID Application: ${SIGNATURE}" --verbose "${FILES}/${APPNAME}.app/Contents/PlugIns/printsupport/libcocoaprintersupport.dylib"

codesign -f -s "Developer ID Application: ${SIGNATURE}" --verbose "${FILES}/${APPNAME}.app/Contents/Resources/libavcodec.55.dylib"
codesign -f -s "Developer ID Application: ${SIGNATURE}" --verbose "${FILES}/${APPNAME}.app/Contents/Resources/libavdevice.55.dylib"
codesign -f -s "Developer ID Application: ${SIGNATURE}" --verbose "${FILES}/${APPNAME}.app/Contents/Resources/libavfilter.4.dylib"
codesign -f -s "Developer ID Application: ${SIGNATURE}" --verbose "${FILES}/${APPNAME}.app/Contents/Resources/libavformat.55.dylib"
codesign -f -s "Developer ID Application: ${SIGNATURE}" --verbose "${FILES}/${APPNAME}.app/Contents/Resources/libavutil.52.dylib"
codesign -f -s "Developer ID Application: ${SIGNATURE}" --verbose "${FILES}/${APPNAME}.app/Contents/Resources/libpostproc.52.dylib"
codesign -f -s "Developer ID Application: ${SIGNATURE}" --verbose "${FILES}/${APPNAME}.app/Contents/Resources/libswresample.0.dylib"
codesign -f -s "Developer ID Application: ${SIGNATURE}" --verbose "${FILES}/${APPNAME}.app/Contents/Resources/libswscale.2.dylib"
codesign -f -s "Developer ID Application: ${SIGNATURE}" --verbose "${FILES}/${APPNAME}.app/Contents/Resources/libopenjpeg.5.dylib"

codesign -f -s "Developer ID Application: ${SIGNATURE}" --verbose "${FILES}/${APPNAME}.app/Contents/MacOS/${APPNAME}"
codesign -f -s "Developer ID Application: ${SIGNATURE}" --verbose "${FILES}/${APPNAME}.app"
cp ../../License.html "${FILES}/License.html"
cp ../../History.txt "${FILES}/History.txt"
mkdir "${FILES}/.background"
cp Logo_White.icns "${FILES}/.background/Logo_White.icns"

# pkg creation
productbuild --component "${FILES}/${APPNAME}.app" /Applications --sign "3rd Party Mac Developer Installer: ${SIGNATURE}" --product "${FILES}/${APPNAME}.app/Contents/Info.plist" "${APPNAME}.pkg"


# Create the disk image
hdiutil create "$DMG" -ov -format UDRW -volname "${APPNAME}" -srcfolder "${FILES}"
DEVICE=$(hdiutil attach -readwrite -noverify "${DMG}" | egrep '^/dev/' | sed 1q | awk '{print $1}')
echo $DEVICE
sleep 2
pushd /Volumes/"${APPNAME}"
ln -s /Applications
rm .DS_Store
popd
echo '
   tell application "Finder"
     tell disk "'${APPNAME}'"
           open
           set current view of container window to icon view
           set toolbar visible of container window to false
           set the bounds of container window to {400, 100, 962, 521}
           set viewOptions to the icon view options of container window
           set arrangement of viewOptions to not arranged
           set icon size of viewOptions to 72
           set background picture of viewOptions to file ".background:Logo_White.icns"
           set position of item "QCTools.app" of container window to {125, 175}
           set position of item "Applications" of container window to {275, 200}
           set position of item "License.html" of container window to {450, 175}
           set position of item "History.txt" of container window to {450, 275}
           close
     end tell
   end tell
' | osascript
hdiutil detach "${DEVICE}"
sleep 2

# convert to compressed image, delete temp image
rm -f "${APPNAME}_${KIND}.dmg"
hdiutil convert "$DMG" -format UDBZ -o "${APPNAME}.dmg"
codesign -f -s "Developer ID Application: ${SIGNATURE}" --verbose "${APPNAME}.dmg"
rm -f "{FILES}"
rm -f "$DMG"
